<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Res\thunder.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Res\thunder.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonTool\CommonTool.csproj" />
    <ProjectReference Include="..\LocalShare.Protocol\LocalShare.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Db\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Res\thunder.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Db\LocalShare.db">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
